language: node_js

node_js:
  - 'node'

cache: yarn

install: yarn

script: yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  target_branch: master
  on:
    branch: source
